# Generated by Django 4.0.3 on 2022-08-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
        ('accounts', '0004_auto_20220801_1910'),
    ]

    operations = [
    ]
