# Generated by Django 4.0.3 on 2022-08-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210313_0218'),
        ('orders', '0008_alter_order_ip'),
    ]

    operations = [
    ]
